### PR TITLE
Respect color scheme preference

### PR DESCRIPTION
**Pull request by illfygli**
The dark theme is hard to read for some people, so I added a media query for this preference, and an alternate light color scheme, doing my best to respect the current design.

### CODE REVIEW

**Comment by Seirdy** [comment]
Should also add a `theme-color` meta tag to the HTML, signalling to browsers that a dark theme is provided. This switches the default stylesheet and turns off auto-dark-mode re-coloring.

**Comment by illfygli** [comment]
@Seirdy Thanks, I didn't know about that one. [Looks like an Apple thing](https://caniuse.com/?search=theme-color)?
I added the tags, but don't have a supported browser, perhaps you can check that I got it right. :)

**Comment by Seirdy** [comment]
Thanks for this PR, it looks like an improvement. In addition to making a light theme, I think we should also improve the dark theme colors. A few things to note:

1. Blue and purple have poor perceptual contrast against dark backgrounds but great perceptual contrast against white backgrounds.
2. The inverse is true for yellower hues
3. Yellow and red are autism-unfriendly colors that can trigger overstimulation, unless they're lightened to pale-yellow and pink or darkened to brown and brick-red.
4. Too much contrast can trigger halation.

I wrote about this a bit in the "dark themes" and "contrast is complex" sections of [a post of mine](https://seirdy.one/2020/11/23/website-best-practices.html#dark-themes).

I'd suggest:

1. Making the dark background color `#111` and the header/footer background `#222`
2. Making the link color `#ffeaba` and the visited link color `#f9dafa` (I kanged those colors from my own site, heh).
3. Making the visited link colors for the light theme a bit less of a harsh red

Much of this isn't really covered in the WCAG; I personally find their color guidelines "necessary but insufficient". Ideally, colors would pass both the WCAG ratios and the Accessible Perceptual Contrast Algorithm ratios, the latter of which will likely be incorporated into WCAG 3.

If you're up for it, you could update the colors in this very PR; if not, I could fix the dark palette in a follow-up PR.

**Comment by illfygli** [comment]
> If you're up for it, you could update the colors in this very PR

Sure, I was just looking at [Reasonable Colors](https://reasonable.work/colors/) for another project.
Perhaps those can be used as a base here as well.

**Comment by illfygli** [comment]
I gave that a try.
I think it looks pretty nice, see how you like it!

**Comment by Seirdy** [comment]
Better, though a solid-black background might cause halation. I make '#0e0e0e' my personal limit.

-- 
/Seirdy

**Comment by illfygli** [comment]
I turned it up a bit.
Once [`prefers-contrast`](https://caniuse.com/?search=prefers-contrast) is more stable, we could use that as well.

**Comment by mcb2003** [comment]
Thanks for the PR, and the comments around contrast and `theme-color` (I didn't know about that either). I'll show this to the other devs, make sure they're happy with it, but this is something I've personally wanted to do, so hopefully we can get this merged.

CC @TTWNO @albertotirla

**Comment by TTWNO** [comment]
The light theme looks great!

The dark-mode link colour are a bit confusing. I couldn't immediately tell which was visited vs. unvisited.
In addition, green/yellow-on-black is not very nice looking design-wise, even if the contrast is "autism friendly" and has "higher perceptual contrast". Any other suggestions on how to make the contrast a bit better in dark mode?

**Comment by illfygli** [comment]
I tried another complementary colour that is more towards blue, but more constrasty than the current blue one. How about that?

**Comment by TTWNO** [comment]
How about azure-3 (#008fdb) for unvisited links?
Works for me as long as everyone else is happy with it. And it keeps it somewhat consistent between light and dark.

**Comment by illfygli** [comment]
Looks a bit dark on my screen, but overall an improvement over the current theme for me. :)

**Pull request merged**
