### PR TITLE
Improve the website layout

### PR DESCRIPTION
**Pull request by thibaultamartin**
- Set a maximum width of 50rem for the main content
- Add 1rem of inline padding so it remains readable on smaller screens (including mobile)
- Make the header stick to the top to be able to quickly jump to another section

Those are very basic CSS changes. I'm not an expert in the field, but I don't think they get in the way of accessibility and improve the reading experience.

### CODE REVIEW

**Comment by thibaultamartin** [comment]
I also realise my "format on save" might have chipped in, but that's likely for the better :)

**Comment by TTWNO** [comment]
Hey! Sorry, thid must have gotten lost deep in my notifications somewhere. Sorry about that.

Taking a look now.

**Comment by TTWNO** [comment]
Looks fine, but why margin-inline instead of margin?

**Comment by TTWNO** [comment]
Absolutely no sticky elements. Please revert that.

Sticky elements are very annoying to those using browser zoom (myself included) as the navigation bar takes more space as you zoom in more.

Since most of our users are visually impaired themselves, this is a big consideration.

**Pull request closed without merging**
